Repository DrKabum/soil-apt, pull requests merged in 2023-09, with the labels that each got.

#21 fix bun path
  .github/workflows/deploy.yml
Labels: devops

#18 Add command to measure API usage
  src/chat-gpt/prompt.ts
  src/commands/usage.ts
  src/data/prompt.ts
  src/helpers/format-big-number.ts
Labels: feature

#24 remove ping command
  src/commands/ping.ts
Labels: refactor

#25 Logging
  .gitignore
  bun.lockb
  package.json
  src/chat-gpt/prompt.ts
  src/helpers/deploy-commands.ts
  src/helpers/handle-commands.ts
  src/helpers/load-commands.ts
  src/helpers/logger.ts
  src/index.ts
Labels: enhancement

#27 Fix/bun file on deployment
  .gitignore
  bun.lockb
Labels: bug, devops

#28 Get all replies on prompt
  src/chat-gpt/open-ai.ts
  src/chat-gpt/prompt.ts
Labels: enhancement

#31 Soil a dit bug
  src/chat-gpt/open-ai.ts
Labels: bug

#32 Persona-of-the-day
  package.json
  src/chat-gpt/open-ai.ts
  src/commands/mood.ts
  src/data/database.ts
  src/data/persona.ts
  src/data/personas.yaml
  src/data/potd.ts
  src/helpers/is-today.ts
  src/helpers/pick-new-potd.ts
  src/index.ts
Labels: feature

#55 Feat/force persona argument
  README.md
  package-lock.json
  package.json
  src/chat-gpt/open-ai.ts
  src/chat-gpt/prompt.ts
  src/helpers/arg-parser.ts
  src/helpers/is-today.ts
  src/helpers/pick-new-potd.ts
  src/helpers/potd-helpers.ts
  src/index.ts
Labels: bug, enhancement

#57 add new personas
  src/data/personas.yaml
Labels: persona

#68 Fix/cd workflows
  .github/workflows/deploy-api.yml
  .github/workflows/deploy-bot.yml
Labels: bug, devops

#72 Replace for a single workflow
  .github/workflows/deploy-api-and-bot.yml
  .github/workflows/deploy-bot.yml
Labels: bug, devops

#73 test without absolute paths for bun cmds
  .github/workflows/deploy-api-and-bot.yml
Labels: bug, devops

#74 change for absolute paths, no package.json script
  .github/workflows/deploy-api-and-bot.yml
Labels: bug, devops
