Repository DrKabum/soil-apt, pull requests merged in 2024-05, with the labels that each got.

#93 🖼️ images support
  api/bun.lockb
  bot/chat-gpt/open-ai.ts
  bot/chat-gpt/prompt.ts
  bot/types.ts
Labels: feature

#95 Fix #94: assign attachements to `system` prompts
  bot/chat-gpt/open-ai.ts
Labels: bug

#96 Remplacement d'une persona inusitée par Patrick Sébastien
  api/data/personas.toml
Labels: persona
